-- MLINI public application schema on Neon (Phase 2).
-- FKs target better_auth."user"(id) — NOT auth.users.
-- NO XP / user.created runtime triggers here (see 002_neon_runtime_triggers.sql).
-- Apply BEFORE historical data import.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY
    REFERENCES better_auth."user"(id) ON DELETE CASCADE,
  username text NULL,
  display_name text NULL,
  avatar_url text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profiles_username_format_check
    CHECK (
      username IS NULL
      OR username ~ '^[A-Za-z0-9_]{3,20}$'
    )
);

-- Exact uniqueness (NULLs allowed multiple times).
CREATE UNIQUE INDEX IF NOT EXISTS profiles_username_key
  ON public.profiles (username);

-- Case-insensitive uniqueness for configured usernames.
CREATE UNIQUE INDEX IF NOT EXISTS profiles_username_lower_unique
  ON public.profiles (lower(username))
  WHERE username IS NOT NULL;

DROP TRIGGER IF EXISTS profiles_set_updated_at ON public.profiles;
CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.user_progress (
  user_id uuid PRIMARY KEY
    REFERENCES better_auth."user"(id) ON DELETE CASCADE,
  total_xp integer NOT NULL DEFAULT 0
    CONSTRAINT user_progress_total_xp_check CHECK (total_xp >= 0),
  current_kingdom_slug text NULL,
  current_mission_slug text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS user_progress_set_updated_at ON public.user_progress;
CREATE TRIGGER user_progress_set_updated_at
  BEFORE UPDATE ON public.user_progress
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.mission_completions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL
    REFERENCES better_auth."user"(id) ON DELETE CASCADE,
  kingdom_slug text NOT NULL,
  mission_slug text NOT NULL,
  xp_awarded integer NOT NULL DEFAULT 0
    CONSTRAINT mission_completions_xp_awarded_check CHECK (xp_awarded >= 0),
  completed_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT mission_completion_unique
    UNIQUE (user_id, kingdom_slug, mission_slug)
);

CREATE INDEX IF NOT EXISTS mission_completions_user_id_idx
  ON public.mission_completions (user_id);

CREATE INDEX IF NOT EXISTS mission_completions_completed_at_idx
  ON public.mission_completions (completed_at DESC);

CREATE TABLE IF NOT EXISTS public.integration_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL
    CONSTRAINT integration_events_event_type_check
      CHECK (event_type = ANY (ARRAY['user.created'::text, 'mission.completed'::text])),
  user_id uuid NULL
    REFERENCES better_auth."user"(id) ON DELETE CASCADE,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS integration_events_event_type_idx
  ON public.integration_events (event_type);

CREATE INDEX IF NOT EXISTS integration_events_created_at_idx
  ON public.integration_events (created_at DESC);

-- Helper marker: runtime XP/user triggers intentionally absent until 002.
COMMENT ON TABLE public.profiles IS
  'MLINI profiles; FK → better_auth.user. Runtime init trigger in 002.';
